server:
  port: 7777

spring:
  application:
    name: api
  config:
    activate:
      on-profile:
        - local
  import:
    - classpath:/application-local.yml
  datasource:
    url: jdbc:h2:~/h2db;
    driverClassName: org.h2.Driver
    username: sa
    password: 
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace
  
 
     